name: Check license header

on:
  pull_request:
  push:
    branches:
      - main
      - master
jobs:
  check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3

    - name: Check License Header
      uses: apache/skywalking-eyes@v0.3.0
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
          config: .github/licenserc.yml
          mode: fix # optional: Which mode License-Eye should be run in. Choices are `check` or `fix`. The default value is `check`.

    - name: Apply Changes
      uses: EndBug/add-and-commit@v4
      with:
        author_name: License Bot
        author_email: license_bot@github.com
        message: 'Automatic application of license header'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
