name: Check license header

on:
  pull_request:
  push:
    branches:
      - main
      - master

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
    - name: Check License Header
      uses: apache/skywalking-eyes@main      # always prefer to use a revision instead of `main`.
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # with:
          # log: debug # optional: set the log level. The default value is `info`.
          config: .github/licenserc.yaml # optional: set the config file. The default value is `.licenserc.yaml`.
          # token: # optional: the token that license eye uses when it needs to comment on the pull request. Set to empty ("") to disable commenting on pull request. The default value is ${{ github.token }}
          # mode: # optional: Which mode License-Eye should be run in. Choices are `check` or `fix`. The default value is `check`.
