name: Check license header

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3

    - name: Check License Header
      uses: apache/skywalking-eyes@main      # always prefer to use a revision instead of `main`.
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
          config: .github/licenserc.yml
          mode: fix # optional: Which mode License-Eye should be run in. Choices are `check` or `fix`. The default value is `check`.
